### PR TITLE
Update expired RPM-GPG-KEY-Mageia

### PR DESCRIPTION
**Pull request by wally-mageia**
Current key is expired long time ago.
```
$ gpg2 --show-key /usr/share/distribution-gpg-keys/mageia/RPM-GPG-KEY-Mageia
pub   rsa4096 2011-02-07 [SCEA] [expired: 2012-03-13]
      00EDB89585B012A8916F0DF8B742FA8B80420F66
uid                      Mageia Packages <packages@mageia.org>
```

New key originally from Mageia mirror [1] is valid until the end of 2025.
```
$ gpg2 --show-key keys/mageia/RPM-GPG-KEY-Mageia
pub   rsa4096 2011-02-07 [SCEA] [expires: 2025-12-31]
      00EDB89585B012A8916F0DF8B742FA8B80420F66
uid                      Mageia Packages <packages@mageia.org>
```

[1] https://mirror.math.princeton.edu/pub/mageia/distrib/cauldron/SRPMS/core/release/media_info/pubkey

### CODE REVIEW

**Comment by wally-mageia** [comment]
Might also fix https://github.com/rpm-software-management/mock/issues/1111.

**Comment by praiskup** [comment]
Thank you for the patch!

> Might also fix https://github.com/rpm-software-management/mock/issues/1111.

Only partly, that issue, in particular, is mostly about the `--use-bootstrap-image` feature.

**Comment by tmzullinger** [comment]
To help verify this key, I was able to confirm that it matches what is found at https://svnweb.mageia.org/ for Mageia [8](https://svnweb.mageia.org/packages/cauldron/mageia-repos/releases/8/1.mga8/SOURCES/RPM-GPG-KEY-Mageia?revision=1675413&view=co) and [9](https://svnweb.mageia.org/packages/cauldron/mageia-repos/releases/9/0.0.5.mga9/SOURCES/RPM-GPG-KEY-Mageia?revision=1939446&view=co).

**Comment by wally-mageia** [comment]
> To help verify this key, I was able to confirm that it matches what is found at https://svnweb.mageia.org/ for Mageia [8](https://svnweb.mageia.org/packages/cauldron/mageia-repos/releases/8/1.mga8/SOURCES/RPM-GPG-KEY-Mageia?revision=1675413&view=co) and [9](https://svnweb.mageia.org/packages/cauldron/mageia-repos/releases/9/0.0.5.mga9/SOURCES/RPM-GPG-KEY-Mageia?revision=1939446&view=co).

Yes, the key is also used in mageia-repos package providing "Mageia package repository files for DNF and PackageKit with GPG public keys".

https://svnweb.mageia.org/packages/cauldron/mageia-repos/current/SOURCES/RPM-GPG-KEY-Mageia?view=log

**Comment by praiskup** [comment]
Thank you all!  I tested Mock builds for Mageia 8 and Mageia Cauldron, and they work fine.

**Pull request merged**
