### PR TITLE
centos: Refresh all SIG keys

### PR DESCRIPTION
**Pull request by Conan-Kudo**
The keys were all regenerated to get rid of the SHA1 algorithm.

The keys are intended to be backwards compatible and can verify CentOS 8 packages.

Also, add a script to make it easier to refresh keys in the future.

See: https://bugzilla.redhat.com/show_bug.cgi?id=2059424

cc: @bstinsonmhk

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
cc: @davide125 @praiskup

**Review by davide125 — APPROVED** [review]
lgtm

**Comment by Conan-Kudo** [comment]
@xsuchy @praiskup Can we get this merged and released asap? It blocks merging and releasing https://pagure.io/centos-sig-hyperscale/mock-centos-sig-configs/pull-request/4

**Comment by praiskup** [comment]
What exactly needs to be released?  Just gpg-keys?  @xsuchy is on PTO, but I could release this tomorrow.

**Comment by Conan-Kudo** [comment]
Just gpg-keys. I need it for Hyperscale's `mock-centos-sig-configs` package.

**Pull request merged**
