### PR TITLE
RPMFusion add fedora-25, old fedora-20 and 21  and el 7 keys (free and nonfree)

### PR DESCRIPTION
**Pull request by sergiomb2**
Hi , Miroslav  , I'm sending to you, new fedora rpmfusion 25 keys.
I still don't have keys for rpmfusion-epel 7 but I will send to you as soon as we get it 

Thanks.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@sergiomb2 Please don't delete GPG keys from distribution-gpg-keys.

**Comment by sergiomb2** [comment]
you mean not delete f22 keys ?

**Comment by Conan-Kudo** [comment]
@sergiomb2 Yes.

**Comment by xsuchy** [comment]
I agree that f22 keys should stay. Can you please alter the PR? Otherwise it looks good.

**Comment by sergiomb2** [comment]
sure , I will do that soon , I'm waiting for GPG keys for el7-rpmfusion

**Comment by sergiomb2** [comment]
Ok now, Pull request just add keys , I don't know if you want old keys for Fedora 20 and 21, if you don't want it , I can remove last commit easily .

Thanks

**Comment by Conan-Kudo** [comment]
@sergiomb2 Why are there symlinks in here? We would probably be using the absolute paths to keys for each mock config in practice, right?

**Comment by xsuchy** [comment]
Merged. Thank you.

**Comment by sergiomb2** [comment]
@Conan-Kudo , legacy  , the real keys are RPM-GPG-KEY-rpmfusion-...-primary , after that we have some keys that link to them: RPM-GPG-KEY-rpmfusion-free-fedora , RPM-GPG-KEY-rpmfusion-free-fedora-latest , RPM-GPG-KEY-rpmfusion-free-fedora-rawhide .
It is safer use the same structure of upstream, if I can remove symlinks in upstream (may take some months) I will update this. 
Thanks.

**Pull request closed without merging**
